-- Run this SQL in the Supabase SQL Editor (or via psql) to create the customers table

CREATE TABLE IF NOT EXISTS public.customers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text,
  email text,
  notes text,
  summary text,
  created_at timestamptz DEFAULT now()
);

-- Optional: create an index on email if you will query by it often
CREATE INDEX IF NOT EXISTS customers_email_idx ON public.customers (email);
